import os
import re

# Comprehensive Dictionary for Arabic Translations
arabic_dictionary = {
    "WELCOME": "مرحباً",
    "RASID": "راصد",
    "User Name": "اسم المستخدم",
    "Password": "كلمة المرور",
    "Forgot Password?": "نسيت كلمة المرور؟",
    "Sign in": "تسجيل الدخول",
    "Please sign in to access the monitoring dashboard.": "يرجى تسجيل الدخول للوصول إلى لوحة المتابعة.",
    "Rasid — A leading professional platform for bug tracking and software quality assurance. Provides a centralized system for monitoring application stability and managing security vulnerabilities through precise analytical reports.": "راصد — منصة احترافية رائدة لتتبع الأخطاء وضمان جودة البرمجيات. يوفر نظاماً مركزياً لمراقبة استقرار التطبيقات وإدارة الثغرات الأمنية من خلال تقارير تحليلية دقيقة.",
    "Core Information": "المعلومات الأساسية",
    "Technical Details & Context": "التفاصيل الفنية والسياق",
    "Assignment & Status": "الإسناد والحالة",
    "Resolution Data": "بيانات الحل",
    "Save Error Report": "حفظ بلاغ الخطأ",
    "Define and manage system properties": "تعريف وإدارة خصائص النظام",
    "Access & Permissions": "الوصول والصلاحيات",
    "Configure screen access and classification": "تهيئة وصول الشاشة وتصنيفها",
    "Group Access": "وصول المجموعات",
    "Manage team permissions and scope": "إدارة صلاحيات ونطاق الفريق",
    "Permissions Scope": "نطاق الصلاحيات",
    "User account settings and role management": "إعدادات حساب المستخدم وإدارة الأدوار",
    "Identity": "الهوية",
    "Access & Roles": "الوصول والأدوار",
    "Back to List": "العودة للقائمة",
    "Resolution details": "تفاصيل الحل",
    "Evidence / Attachment": "الدليل / المرفقات",
    "Discussion": "المناقشة",
    "No communication on this issue yet.": "لا يوجد تواصل بشأن هذا الخطأ بعد.",
    "Post Comment": "نشر تعليق",
    "Information": "المعلومات",
    "System": "النظام",
    "Screen": "الشاشة",
    "Assignee": "المسند إليه",
    "Target Team": "الفريق المستهدف",
    "Last Update": "آخر تحديث",
    "History Timeline": "سجل الأحداث",
    "Zero activity recorded.": "لم يتم تسجيل أي نشاط.",
    "Mark as Fixed": "تحديد كمصلح",
    "View Details": "عرض التفاصيل",
    "Cancel": "إلغاء",
    "Save System": "حفظ النظام",
    "Save Screen": "حفظ الشاشة",
    "Save Group": "حفظ المجموعة",
    "Save User": "حفظ المستخدم",
    "Systems Accessible": "الأنظمة المتاحة",
    "Specific Screens Assigned": "شاشات محددة مسندة",
    "My Dashboard": "لوحة التحكم الخاصة بي",
    "Select a system below to track its errors and operational progress.": "اختر نظاماً أدناه لتتبع أخطائه وسير العمليات فيه.",
    "My Systems": "أنظمتي",
    "No description provided.": "لا يوجد وصف متوفر.",
    "Enter Dashboard": "دخول لوحة التحكم",
    "No Operational Access": "لا يوجد صلاحية وصول عملياتية",
    "You are not currently assigned to any systems.": "أنت غير مسند لأي أنظمة حالياً.",
    "Your assigned systems represent the environments you are authorized to monitor.": "الأنظمة المسندة إليك تمثل البيئات التي لديك صلاحية مراقبتها.",
    "Excellent! Issue #%(id)s has been marked as Resolved.": "ممتاز! تم تحديد الخطأ رقم %(id)s كمحلول بنجاح.",
    "This report was auto-generated by the Bug Tracking System - OpenSoft Company": "تم توليد هذا التقرير تلقائياً بواسطة نظام تعقب الأخطاء - شركة أوبن سوفت",
    "Generate a complete report with no filters. Includes all systems, teams, and statuses.": "توليد تقرير كامل بدون فلاتر. يشمل جميع الأنظمة والفرق والحالات.",
    "This action will cascade and delete all associated screens, teams, issues, and comments. This is a highly destructive action.": "سيؤدي هذا الإجراء لحذف كافة الشاشات والفرق والأخطاء والتعليقات المرتبطة. هذا إجراء تدميري لا يمكن التراجع عنه.",
    "This action cannot be undone and will delete all associated comments and activity logs.": "هذا الإجراء نهائي وسيؤدي لحذف كافة التعليقات وسجلات النشاط المرتبطة.",
    "Generate, filter, and print official audit reports for all teams and systems.": "توليد وتصفية وطباعة تقارير التدقيق الرسمية لكافة الفرق والأنظمة.",
    "You are not authorized to resolve this issue.": "ليس لديك صلاحية لحل هذا الخطأ.",
    "The report opens in a new print-ready window. You can save it as PDF from the browser.": "سيفتح التقرير في نافذة جديدة جاهزة للطباعة. يمكنك حفظه كـ PDF من المتصفح.",
    "Please coordinate with your superior to obtain the necessary credentials.": "يرجى التنسيق مع مديرك المباشر للحصول على بيانات الاعتماد اللازمة.",
    "Note: Deleting a team will leave its members without a team assignment but will not delete the users.": "ملاحظة: حذف الفريق سيترك أعضاءه بدون فريق ولكن لن يحذف حسابات المستخدمين.",
    "Warning: Deleting a user will also delete all issues they reported and all comments they posted.": "تحذير: حذف المستخدم سيؤدي أيضاً لحذف كافة الأخطاء والتعليقات التي قام بنشرها.",
    "Quick Resolve": "حل سريع",
    "This issue is already resolved or closed.": "هذا الخطأ محلول أو مغلق بالفعل.",
    "There are currently no users registered in the system.": "لا يوجد مستخدمون مسجلون في النظام حالياً.",
    "We couldn't find any items matching your current view.": "لم نتمكن من العثور على أي عناصر تطابق العرض الحالي.",
    "Version": "الإصدار",
    "for stability": "لضمان الاستقرار",
    "to": "إلى",
    "Delete System": "حذف النظام",
    "Delete Screen": "حذف الشاشة",
    "Stakeholders": "المعنيون",
    "Systems Access": "الوصول للأنظمة",
    "Avatar": "الصورة الرمزية",
    "Recipient": "المسلم",
    "Message": "الرسالة",
    "Is Read": "تمت القراءة",
    "Other": "أخرى",
    "Delete Group": "حذف المجموعة",
    "Screenshot": "لقطة شاشة",
    "%(timesince)s ago": "منذ %(timesince)s",
    "Add New System": "إضافة نظام جديد",
    "Add New Group": "إضافة مجموعة جديدة",
    "Add New Screen": "إضافة شاشة جديدة",
    "Edit Error: %(title)s": "تعديل الخطأ: %(title)s",
    "Edit System: %(name)s": "تعديل النظام: %(name)s",
    "Edit Group: %(name)s": "تعديل المجموعة: %(name)s",
    "Edit Screen: %(name)s": "تعديل الشاشة: %(name)s",
    "Profile updated successfully.": "تم تحديث الملف الشخصي بنجاح.",
    "Password changed successfully.": "تم تغيير كلمة المرور بنجاح.",
    "Status Changed (Inline)": "تغيير الحالة (سريع)",
    "Comment Added": "تم إضافة تعليق",
    "Comment added successfully.": "تم إضافة التعليق بنجاح.",
    "Please fill in the technical details accurately": "يرجى تعبئة التفاصيل الفنية بدقة",
}

def force_translate_po(po_file_path):
    if not os.path.exists(po_file_path):
        print(f"File not found: {po_file_path}")
        return

    # Read the file with multiple encodings fallback
    content = None
    for enc in ['utf-8', 'windows-1256', 'iso-8859-6']:
        try:
            with open(po_file_path, 'r', encoding=enc) as f:
                content = f.read()
            print(f"Successfully read with {enc}")
            break
        except UnicodeDecodeError:
            continue
    
    if content is None:
        print("Failed to read PO file with any supported encoding.")
        return

    # Process lines
    lines = content.splitlines()
    new_lines = []
    current_msgid = ""
    
    for line in lines:
        if line.startswith('msgid "'):
            # Extract id and clean it
            match = re.search(r'msgid "(.*)"', line)
            current_msgid = match.group(1).strip() if match else ""
            new_lines.append(line)
        elif line.startswith('msgstr "'):
            # Check for direct match or stripped match
            if current_msgid in arabic_dictionary:
                new_lines.append(f'msgstr "{arabic_dictionary[current_msgid]}"')
            elif current_msgid.strip() in arabic_dictionary:
                 new_lines.append(f'msgstr "{arabic_dictionary[current_msgid.strip()]}"')
            else:
                new_lines.append(line)
        else:
            new_lines.append(line)

    # Write back as UTF-8 with BOM to help Windows recognize it
    with open(po_file_path, 'w', encoding='utf-8-sig') as f:
        f.write("\n".join(new_lines))

    print("PO file force-translated and saved as UTF-8.")

if __name__ == "__main__":
    force_translate_po('locale/ar/LC_MESSAGES/django.po')
