import io
import os

path = r'locale\ar\LC_MESSAGES\django.po'

# Read file as bytes to clean up UTF-16 artifacts at the end
with io.open(path, 'rb') as f:
    content = f.read()

# Find the start of the corrupted part (null bytes)
clean_content = content.split(b'\x00')[0]

# we might chop off a valid byte if we just split by null, but the corruption started with 'm\x00s\x00g' so let's find that.
corrupt_start = content.find(b'm\x00s\x00g\x00i\x00d')
if corrupt_start != -1:
    clean_content = content[:corrupt_start]

# Write the clean content back
with io.open(path, 'wb') as f:
    f.write(clean_content)

# Append the new records in UTF-8
new_records = """
msgid "Technical Report: Software Issues Logging & Reporting"
msgstr "تقرير فني: حصر وبلاغات المشاكل البرمجية"

msgid "This report was auto-generated by the Bug Tracking System - OpenSoft Company"
msgstr "تم استخراج هذا التقرير آلياً من نظام إدارة وتتبع البلاغات - شركة OpenSoft"
"""

with io.open(path, 'a', encoding='utf-8') as f:
    f.write(new_records)

print("Fixed")
