import os
import re

# Comprehensive Dictionary for Arabic Translations
# Using the exact strings from HTML to ensure matching
arabic_dictionary = {
    "WELCOME": "مرحباً بك في نظام",
    "RASID": "راصد لمراقبة جودة الأنظمة",
    "User Name": "اسم المستخدم",
    "Password": "كلمة المرور",
    "Forgot Password?": "نسيت كلمة المرور؟",
    "Sign in": "تسجيل الدخول للنظام",
    "Please sign in to access the monitoring dashboard.": "يرجى إدخال بيانات الاعتماد للوصول إلى لوحة المراقبة المركزية.",
    "Rasid — A leading professional platform for bug tracking and software quality assurance. Provides a centralized system for monitoring application stability and managing security vulnerabilities through precise analytical reports.": "نظام راصد — المنصة المتخصصة في إدارة وتتبع الأخطاء البرمجية وضمان جودة الأنظمة. يوفر النظام بيئة عمل متكاملة لمراقبة استقرار التطبيقات ومعالجة الثغرات الأمنية عبر تقارير فنية وتحليلية دقيقة.",
    "Errors List": "قائمة الأخطاء التقنية",
    "Add Error": "إضافة خطأ جديد",
    "Confirm Status Change": "تأكيد تغيير الحالة",
    "Are you sure you want to change the status of this error?": "هل أنت متأكد من رغبتك في تغيير حالة هذا الخطأ؟",
    "Target Status": "الحالة المستهدفة",
    "Confirm Update": "تأكيد التحديث",
    "Update Successful": "تم التحديث بنجاح",
    "The error status has been synchronized across the system.": "تمت مزامنة حالة الخطأ في النظام بنجاح.",
    "OK": "موافق",
    "Updating...": "جاري التحديث...",
    "Transition To": "نقل إلى حالة",
    "Good Morning": "صباح الخير",
    "Good Afternoon": "مساء الخير",
    "Good Evening": "مساء الخير",
    "Core Information": "البيانات الأساسية",
    "Technical Details & Context": "البيانات الفنية والسياق التشغيلي",
    "Assignment & Status": "حالة التكليف والمتابعة",
    "Resolution Data": "تفاصيل المعالجة والحل",
    "Save Error Report": "حفظ بيانات الخطأ",
    "Define and manage system properties": "تعريف وإدارة خصائص النظام",
    "Access & Permissions": "الوصول والصلاحيات",
    "Configure screen access and classification": "تهيئة وصول الشاشة وتصنيفها",
    "Group Access": "وصول المجموعات",
    "Manage team permissions and scope": "إدارة صلاحيات ونطاق الفريق",
    "Permissions Scope": "نطاق الصلاحيات",
    "User account settings and role management": "إعدادات حساب المستخدم وإدارة الأدوار",
    "Identity": "الهوية",
    "Access & Roles": "الوصول والأدوار",
    "Back to List": "الرجوع للقائمة",
    "Resolution details": "تفاصيل المعالجة",
    "Evidence / Attachment": "المرفقات والوثائق المؤيدة",
    "Discussion": "سجل التواصل",
    "No communication on this issue yet.": "لا توجد مراسلات بشأن هذا الخطأ حتى الآن.",
    "Post Comment": "إضافة تعقيب",
    "Information": "المعلومات",
    "System": "النظام",
    "Screen": "الشاشة",
    "Assignee": "المسند إليه",
    "Target Team": "الفريق المختص",
    "Last Update": "تاريخ آخر تحديث",
    "History Timeline": "سجل الأحداث المخطط",
    "Zero activity recorded.": "لا توجد أنشطة مسجلة حالياً.",
    "Mark as Fixed": "تحديد كمعالج",
    "View Details": "عرض التفاصيل",
    "Cancel": "إلغاء",
    "Save System": "حفظ النظام",
    "Save Screen": "حفظ الشاشة",
    "Save Group": "حفظ المجموعة",
    "Save User": "حفظ المستخدم",
    "Systems Accessible": "الأنظمة المتاحة",
    "Specific Screens Assigned": "الشاشات المسندة",
    "My Dashboard": "لوحة التحكم",
    "Select a system below to track its errors and operational progress.": "يرجى اختيار النظام لمتابعة الأخطاء وسير العمليات.",
    "My Systems": "الأنظمة المسندة",
    "No description provided.": "لا يوجد وصف متوفر حالياً.",
    "Enter Dashboard": "دخول النظام",
    "No Operational Access": "لا يوجد صلاحية وصول عملياتية",
    "You are not currently assigned to any systems.": "الحساب غير مرتبط بأي أنظمة حالياً.",
    "Your assigned systems represent the environments you are authorized to monitor.": "الأنظمة المتاحة تمثل البيئات المصرح لك بمراقبتها.",
    "Excellent! Issue #%(id)s has been marked as Resolved.": "تم تحديث حالة الخطأ رقم %(id)s إلى 'مكتمل' بنجاح.",
    "This report was auto-generated by the Bug Tracking System - OpenSoft Company": "تم توليد هذا التقرير تلقائياً بواسطة نظام راصد - شركة أوبن سوفت",
    "Generate a complete report with no filters. Includes all systems, teams, and statuses.": "توليد تقرير شامل بدون فلاتر لجميع الأنظمة والفرق والحالات.",
    "This action will cascade and delete all associated screens, teams, issues, and comments. This is a highly destructive action.": "سيؤدي هذا الإجراء لحذف كافة الشاشات والفرق والأخطاء والتعليقات المرتبطة. هذا إجراء نهائي.",
    "This action cannot be undone and will delete all associated comments and activity logs.": "هذا الإجراء نهائي وسيؤدي لحذف كافة التعقيبات وسجلات الأنشطة المرتبطة.",
    "Generate, filter, and print official audit reports for all teams and systems.": "توليد وتصفية وطباعة تقارير التدقيق الرسمية لكافة الفرق والأنظمة.",
    "You are not authorized to resolve this issue.": "لا تملك الصلاحية اللازمة لمعالجة هذا الخطأ.",
    "The report opens in a new print-ready window. You can save it as PDF from the browser.": "سيتم عرض التقرير في نافذة منفصلة جاهزة للطباعة أو الحفظ كملف PDF.",
    "Please coordinate with your superior to obtain the necessary credentials.": "يرجى التنسيق مع الإدارة المختصة للحصول على صلاحيات الوصول اللازمة.",
    "Note: Deleting a team will leave its members without a team assignment but will not delete the users.": "ملاحظة: حذف الفريق لا يؤدي لحذف حسابات المستخدمين المرتبطين به.",
    "Warning: Deleting a user will also delete all issues they reported and all comments they posted.": "تحذير: حذف المستخدم سيؤدي لحذف كافة الأخطاء والتعقيبات التي قام بنشرها.",
    "Quick Resolve": "معالجة سريعة",
    "This issue is already resolved or closed.": "هذا الخطأ تم معالجته أو إغلاقه مسبقاً.",
    "There are currently no users registered in the system.": "لا يوجد مستخدمون مسجلون في النظام حالياً.",
    "We couldn't find any items matching your current view.": "لم يتم العثور على أي نتائج تطابق معايير العرض الحالية.",
    "Version": "الإصدار",
    "for stability": "لضمان الاستقرار",
    "to": "إلى",
    "Delete System": "حذف النظام",
    "Delete Screen": "حذف الشاشة",
    "Stakeholders": "الأطراف المعنية",
    "Systems Access": "الوصول للأنظمة",
    "Avatar": "الصورة الرمزية",
    "Recipient": "المستلم",
    "Message": "الرسالة",
    "Is Read": "تمت القراءة",
    "Other": "أخرى",
    "Delete Group": "حذف المجموعة",
    "Screenshot": "لقطة شاشة",
    "%(timesince)s ago": "منذ %(timesince)s",
    "Add New System": "إضافة نظام جديد",
    "Add New Group": "إضافة مجموعة جديدة",
    "Add New Screen": "إضافة شاشة جديدة",
    "Edit Error: %(title)s": "تعديل بيانات الخطأ: %(title)s",
    "Edit System: %(name)s": "تعديل النظام: %(name)s",
    "Edit Group: %(name)s": "تعديل المجموعة: %(name)s",
    "Edit Screen: %(name)s": "تعديل الشاشة: %(name)s",
    "Profile updated successfully.": "تم تحديث الملف الشخصي بنجاح.",
    "Password changed successfully.": "تم تغيير كلمة المرور بنجاح.",
    "Status Changed (Inline)": "تغيير الحالة (سريع)",
    "Comment Added": "تم إضافة تعقيب",
    "Comment added successfully.": "تم إضافة التعقيب بنجاح.",
    "Please fill in the technical details accurately": "يرجى تعبئة البيانات الفنية بدقة",
    "Configure screen access and classification": "تهيئة وصول الشاشة وتصنيفها",
    "Group Access": "وصول المجموعات",
    "Security": "الأمنية",
    "Welcome back": "مرحباً بك مجدداً",
    "My Tasks": "المهام المسندة",
    "View All Errors": "عرض كافة الأخطاء",
    "Report Error": "إبلاغ عن خطأ",
    "Health Score": "مؤشر الاستقرار التشغيلي",
    "View My Profile": "عرض الملف الشخصي",
    "Team Authorized": "صلاحية الفريق الفني",
    "Bug": "خطأ تقني",
    "UI": "واجهة المستخدم",
    "Low": "منخفض",
    "Medium": "متوسط",
    "High": "مرتفع",
    "Critical": "حرج للغاية",
    "Open": "قيد الانتظار",
    "In Progress": "قيد المعالجة",
    "Resolved": "مكتمل / معالج",
    "Closed": "مغلق نهائياً",
    "Reopened": "أعيد فتحه للمراجعة",
    "Fixed": "تم الإصلاح بنجاح",
    "Duplicate": "بلاغ مكرر",
    "Won't Fix": "لن يتم اتخاذ إجراء",
    "Works For Me": "لا يمكن إعادة إنتاج الخطأ",
    "Not a Bug": "ليس خطأً تقنياً",
    "Unresolved": "بانتظار المعالجة",
    "Admin": "مدير النظام",
    "FrontEnd": "Frontend Developer - مطور الواجهات الأمامية",
    "BackEnd": "Backend Developer - مطور الواجهات الخلفية",
    "Specific Screens Assigned": "الشاشات المسندة",
}

header_text = r'''msgid ""
msgstr ""
"Project-Id-Version: PACKAGE VERSION\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2026-04-21 12:00+0000\n"
"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"Language: ar\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Plural-Forms: nplurals=6; plural=n==0 ? 0 : n==1 ? 1 : n==2 ? 2 : n%100>=3 && n%100<=10 ? 3 : n%100>=11 && n%100<=99 ? 4 : 5;\n"

'''

def ultimate_fix_v3(po_file_path):
    if not os.path.exists(po_file_path):
        return

    # Read existing entries
    with open(po_file_path, 'rb') as f:
        raw_data = f.read()

    try:
        content = raw_data.decode('utf-8')
    except:
        content = raw_data.decode('latin-1')

    lines = content.splitlines()
    entries = {} # Use dict to store latest msgstr for each msgid
    current_id = None
    
    for line in lines:
        line = line.strip()
        if not line or line.startswith('#'): continue
            
        if line.startswith('msgid "'):
            match = re.search(r'msgid "(.*)"', line)
            current_id = match.group(1) if match else None
            if current_id == "": current_id = None # Skip header
            elif current_id not in entries:
                entries[current_id] = ""
        elif line.startswith('msgstr "') and current_id is not None:
            match = re.search(r'msgstr "(.*)"', line)
            entries[current_id] = match.group(1) if match else ""
            current_id = None

    # Merge with dictionary (ADD missing ones)
    for mid, mstr in arabic_dictionary.items():
        # Always update or add from dictionary
        entries[mid] = mstr

    # Rebuild file
    with open(po_file_path, 'w', encoding='utf-8') as f:
        f.write(header_text)
        for mid, mstr in entries.items():
            f.write(f'msgid "{mid}"\n')
            f.write(f'msgstr "{mstr}"\n\n')

    print("PO file rebuilt and UPDATED with all dictionary strings.")

if __name__ == "__main__":
    ultimate_fix_v3('locale/ar/LC_MESSAGES/django.po')
