# Generated by Django 5.2.12 on 2026-04-07 08:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='system',
        ),
        migrations.RemoveField(
            model_name='user',
            name='team',
        ),
        migrations.AddField(
            model_name='team',
            name='systems',
            field=models.ManyToManyField(blank=True, related_name='teams', to='core.system', verbose_name='Systems'),
        ),
        migrations.AddField(
            model_name='user',
            name='teams',
            field=models.ManyToManyField(blank=True, related_name='members', to='core.team', verbose_name='Teams'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(verbose_name='Comment Content'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='issue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='core.issue', verbose_name='Issue'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='actual_result',
            field=models.TextField(blank=True, null=True, verbose_name='Actual Result'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_issues', to=settings.AUTH_USER_MODEL, verbose_name='Assigned To'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='expected_result',
            field=models.TextField(blank=True, null=True, verbose_name='Expected Result'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='issues/images/', verbose_name='Image Attachment'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='issue_type',
            field=models.CharField(choices=[('bug', 'Bug'), ('security', 'Security'), ('ui', 'UI')], max_length=20, verbose_name='Issue Type'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20, verbose_name='Priority'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='reported_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reported_issues', to=settings.AUTH_USER_MODEL, verbose_name='Reported By'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='screen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='core.screen', verbose_name='Screen'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('closed', 'Closed'), ('reopened', 'Reopened')], default='open', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='steps_to_reproduce',
            field=models.TextField(blank=True, null=True, verbose_name='Steps to Reproduce'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='system',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='core.system', verbose_name='System'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='issuelog',
            name='action',
            field=models.CharField(max_length=255, verbose_name='Action'),
        ),
        migrations.AlterField(
            model_name='issuelog',
            name='changed_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issue_logs', to=settings.AUTH_USER_MODEL, verbose_name='Changed By'),
        ),
        migrations.AlterField(
            model_name='issuelog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='issuelog',
            name='issue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='core.issue', verbose_name='Issue'),
        ),
        migrations.AlterField(
            model_name='issuelog',
            name='new_value',
            field=models.TextField(blank=True, null=True, verbose_name='New Value'),
        ),
        migrations.AlterField(
            model_name='issuelog',
            name='old_value',
            field=models.TextField(blank=True, null=True, verbose_name='Old Value'),
        ),
        migrations.AlterField(
            model_name='screen',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='screen',
            name='system',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screens', to='core.system', verbose_name='System'),
        ),
        migrations.AlterField(
            model_name='system',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='system',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is Active'),
        ),
        migrations.AlterField(
            model_name='system',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('supervisor', 'Supervisor'), ('member', 'Member')], default='member', max_length=20, verbose_name='Role'),
        ),
    ]
