# Generated by Django 5.2.12 on 2026-04-07 12:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_team_system_remove_user_team_team_systems_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='leader',
            field=models.ForeignKey(blank=True, limit_choices_to={'role__in': ['admin', 'supervisor']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_teams', to=settings.AUTH_USER_MODEL, verbose_name='Team Leader'),
        ),
        migrations.AddField(
            model_name='team',
            name='screens',
            field=models.ManyToManyField(blank=True, related_name='teams', to='core.screen', verbose_name='Assigned Screens'),
        ),
    ]
