# Generated by Django 5.2.12 on 2026-04-07 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0003_team_leader_team_screens'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='teams',
        ),
        migrations.AddField(
            model_name='screen',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='Groups that have access to this specific screen.', related_name='screens', to='auth.group', verbose_name='Groups'),
        ),
        migrations.AddField(
            model_name='system',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='Groups that have access to this system.', related_name='systems', to='auth.group', verbose_name='Groups'),
        ),
        migrations.DeleteModel(
            name='Team',
        ),
    ]
