# Generated by Django 5.2.12 on 2026-04-11 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_user_teams_screen_groups_system_groups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='target_team',
            field=models.CharField(choices=[('frontend', 'FrontEnd'), ('backend', 'BackEnd')], default='frontend', max_length=20, verbose_name='Target Team'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('frontend', 'FrontEnd'), ('backend', 'BackEnd')], default='frontend', max_length=20, verbose_name='Role'),
        ),
    ]
