# Generated by Django 5.2.12 on 2026-04-11 07:15

from django.db import migrations


def migrate_roles_forward(apps, schema_editor):
    """Convert old roles to new roles:
    - 'supervisor' → 'admin'
    - 'member'     → 'frontend'
    """
    User = apps.get_model('core', 'User')
    User.objects.filter(role='supervisor').update(role='admin')
    User.objects.filter(role='member').update(role='frontend')


def migrate_roles_backward(apps, schema_editor):
    """Revert new roles back to old roles (best-effort):
    - 'frontend' → 'member'
    - 'backend'  → 'member'
    """
    User = apps.get_model('core', 'User')
    User.objects.filter(role='frontend').update(role='member')
    User.objects.filter(role='backend').update(role='member')


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_add_frontend_backend_roles_and_target_team'),
    ]

    operations = [
        migrations.RunPython(migrate_roles_forward, migrate_roles_backward),
    ]
