# Generated by Django 5.1.4 on 2026-04-14 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_migrate_old_roles_to_new'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='resolution',
            field=models.CharField(choices=[('fixed', 'Fixed'), ('duplicate', 'Duplicate'), ('wont_fix', "Won't Fix"), ('works_for_me', 'Works For Me'), ('not_a_bug', 'Not a Bug'), ('unresolved', 'Unresolved')], default='unresolved', max_length=20, verbose_name='Resolution'),
        ),
        migrations.AddField(
            model_name='issue',
            name='root_cause',
            field=models.TextField(blank=True, null=True, verbose_name='Root Cause'),
        ),
    ]
