# Generated by Django 5.1.4 on 2026-04-19 07:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_notification'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='issue',
            options={'ordering': ['-created_at'], 'verbose_name': 'Error', 'verbose_name_plural': 'Errors'},
        ),
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='users/avatars/', verbose_name='Avatar'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='issue_type',
            field=models.CharField(choices=[('bug', 'Bug'), ('security', 'Security'), ('ui', 'UI')], max_length=20, verbose_name='Error Type'),
        ),
        migrations.AlterField(
            model_name='issuelog',
            name='issue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='core.issue', verbose_name='Error'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='issue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='core.issue', verbose_name='Error'),
        ),
    ]
