# Generated by Django 5.1.4 on 2026-04-21 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0009_alter_issue_options_user_avatar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='target_team',
            field=models.CharField(choices=[('frontend', 'FrontEnd'), ('backend', 'BackEnd'), ('security', 'Security')], default='frontend', max_length=20, verbose_name='Target Team'),
        ),
        migrations.AlterField(
            model_name='screen',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='screens', to='auth.group', verbose_name='Groups'),
        ),
        migrations.AlterField(
            model_name='system',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='systems', to='auth.group', verbose_name='Groups'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('frontend', 'FrontEnd'), ('backend', 'BackEnd'), ('security', 'Security')], default='frontend', max_length=20, verbose_name='Role'),
        ),
    ]
